### ISSUE TITLE
could you please give a button like this

### ISSUE THREAD

**Issue by ericyan71** [ColinDuquesnoy/QDarkStyleSheet#120]
hello, I'm learning pyqt5 now, and I found this awesome dark-style, I very like this style, thanks!

now, I want to make a button or other control, it looks like the picture below:

![eric20181111183952](https://user-images.githubusercontent.com/22901866/48311877-456d6680-e5e1-11e8-969f-4e4e1875f22c.png)

it looks that there are two borders, the outer is deep dark, and the inner is some lighter, I tried more than one day, but can't get this effect, could you please help me and give a qss example? thanks!

**Comment by dpizetta** [comment]
Hi @ericyan71, thanks!
About the button, we cannot provide that because qdarkstyle is already a style in a flat mode with a rounded border. In version 3 we will have some other types, where we can change the color palette, or the borders for example. However, such a modification using gradients it is too far for us. 

If help, you can see some examples here:

https://www.tardigrada.co/blog/2010/09/custom-push-buttons-on-the-n900-with-qt-style-sheets/

https://doc-snapshots.qt.io/4.8/qtwebkit-guide-css.html
https://doc-snapshots.qt.io/4.8/webkit-webkit-guide-css-css3-gradientbutton-css.html

Tks! So I will close this issue for know.
