### ISSUE TITLE
QPushButton size differs significantly w/ or w/o qdarkstyle in version 2.8

### ISSUE THREAD

**Issue by mvillion** [ColinDuquesnoy/QDarkStyleSheet#230]
### Describe Your Environment
* OPERATING SYSTEM---------------------------------------------------------------
    - System........................ Linux
    - Release....................... 5.3.0-42-generic
    - Platform...................... Linux-5.3.0-42-generic-x86_64-with-Ubuntu-19.10-eoan
    - Version....................... #34-Ubuntu SMP Fri Feb 28 05:49:40 UTC 2020
* PYTHON DISTRIBUTION------------------------------------------------------------
    - Version....................... 3.7.5
    - C Compiler.................... GCC 9.2.1 20191008
    - C API Version................. 1013
    - Implementation................ cpython
    - Implementation Version........ 3.7.5
* QT BINDINGS--------------------------------------------------------------------
    - PyQt5 Version................. 5.13.2
    - PyQt5 Qt Version.............. 5.13.2
    - PySide2 Version............... 5.13.0
    - PySide2 Qt Version............ 5.13.2
* QT ABSTRACTIONS----------------------------------------------------------------
    - qtpy Version.................. 1.9.0
    - qtpy Binding.................. pyqt5
    - qtpy Binding Variable......... os.environ['QT_API']
    - qtpy Import Name.............. qtpy
    - qtpy Status................... OK
    - pyqtgraph Version............. 0.10.0
    - pyqtgraph Binding............. Not set or inexistent
    - pyqtgraph Binding Variable.... os.environ['PYQTGRAPH_QT_LIB']
    - pyqtgraph Import Name......... pyqtgraph
    - pyqtgraph Status.............. OK
* PYTHON PACKAGES----------------------------------------------------------------
qdarkstyle version 2.8

### Description / Steps to Reproduce [if necessary]

Hello,

I am in an opposite situation to issue #194

When playing with the size of QPushButton, the behavior with qdarkstyle 2.8 differs from the reference behavior. In version 2.8, I did not find a solution to produce short buttons.

### Actual Result
without qdarkstyle:
![image](https://user-images.githubusercontent.com/18051403/77749149-d0f26680-7021-11ea-82ce-c3175e5843b2.png)

with qdarkstyle:
![image](https://user-images.githubusercontent.com/18051403/77749563-845b5b00-7022-11ea-8460-d0b28d520a26.png)

### Expected Results / Proposed Result
Button sizes with qdarkstyle should be the same as without.

### Relevant Code

```
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import qdarkstyle

from PyQt5.QtCore import QSize
from PyQt5.QtWidgets import QApplication
from PyQt5.QtWidgets import QHBoxLayout
from PyQt5.QtWidgets import QPushButton
from PyQt5.QtWidgets import QWidget


class ShortButton(QPushButton):
    def __init__(self, text, min_size, *arg, **kwarg):
        QPushButton.__init__(self, text, *arg, **kwarg)
        self.min_size = min_size

    def minimumSizeHint(self):
        size = QPushButton.minimumSizeHint(self)
        return QSize(self.min_size, size.height())

    def sizeHint(self):
        size = QPushButton.sizeHint(self)
        return QSize(self.min_size, size.height())


class App(QWidget):

    def __init__(self):
        QWidget.__init__(self)
        self.setWindowTitle("button")
        large = QPushButton("Very large button")
        short = QPushButton("x")
        short.setMaximumWidth(20)
        another_short = ShortButton("y", 20)

        l_ = QHBoxLayout()
        l_.addWidget(large)
        l_.addWidget(short)
        l_.addWidget(another_short)

        self.setLayout(l_)
        self.show()


if __name__ == "__main__":
    app = QApplication([])
    # dark_stylesheet = qdarkstyle.load_stylesheet_from_environment()
    # app.setStyleSheet(dark_stylesheet)
    ex = App()
    app.exec_()
```

**Comment by dpizetta** [comment]
Hi, @mvillion, I think that the appropriate button you can use is the tool button instead, looking at your application. PushButton and ToolButton are practically the same, so, I think you can use it. Take a look at #217.

**From the QPushButton Docs:** 

"As a general rule, use a push button when the application or dialog window performs an action when the user clicks on it (such as Apply, Cancel, Close and Help) and when the widget is supposed to have a wide, rectangular shape with a text label. Small, typically square buttons that change the state of the window rather than performing an action (such as the buttons in the top-right corner of the QFileDialog) are not command buttons, but tool buttons. Qt provides a special class (QToolButton) for these buttons.

If you need toggle behavior (see setCheckable()) or a button that auto-repeats the activation signal when being pushed down like the arrows in a scroll bar (see setAutoRepeat()), a command button is probably not what you want. When in doubt, use a tool button.
"

**References in importance order:**

    - [QPushButton docs](https://doc.qt.io/qt-5/qpushbutton.html)
    - [QToolButton docs](https://doc.qt.io/qt-5/qtoolbutton.html)
    - [Qt forum](https://www.qtcentre.org/threads/37146-pushButton-and-toolButton)

I think we can put these comments and docs as a "known issue", so more people can look at it.

Related to: #194, #217, #230

Tks

**Comment by mvillion** [comment]
Thank you dpizettta for this suggestion.
Use of QToolButton is as a valid alternative.
