### ISSUE TITLE
Design new color system based on Ux improvements

### ISSUE THREAD

**Issue by juanis2112** [ColinDuquesnoy/QDarkStyleSheet#252]
Our UX/UI expert @isabela-pf has been helping us (Spyder team) to design a new color system for the dark and light styles so we will implement it for QDarkStyle as discussed in a meeting with @dpizetta and @ccordoba12 

Here is the system proposed https://github.com/spyder-ide/ux-improvements/issues/13

**Comment by isabela-pf** [comment]
Since the linked issue focuses on how we decided the system and colors, I thought it might be useful to give an overview of the proposed changes here.
- Set up QDarkStyle as a more flexible framework where it is easy to modify or make your own themes on top of the existing palette.
- Add a color system (numbered set of values for each color) that the palette imports. This helps make palettes easier to adjust in the future.
- Revise constant names with the intended use of those colors.
- Maintain a default dark palette that looks similar to the current version (from a user perspective).
- Add a default light palette (with colors related to dark mode).
- Add documentation explaining the system.

Feedback, questions, and comments are welcome!

**Comment by dpizetta** [comment]
Thanks @isabela-pf and @ccordoba12. I will test our scripts, today is not online. We were using that pallet to generate the png files from sgv ones, so if we change the pallet we need to generate new ones, so it does not need that who download to run and create png or resources files. This is a point we have established some time ago, so we can reduce the need for problematic dependencies but we increase the size of our package by adding images.

**Comment by Daguerreo** [comment]
@dpizetta it will via available from C++ via qss?

**Comment by dpizetta** [comment]
@Daguerreo sure it does! :)
