### ISSUE TITLE
transparent.png not found

### ISSUE THREAD

**Issue by sabrabano0** [ColinDuquesnoy/QDarkStyleSheet#286]
in qt5.15 c++:
transparent.png not found

in your repo there isn't any transparent.png 
how could i solve this?

**Comment by sabrabano0** [comment]
:-1: error: dependent '..\myproject\qdarkstyle\theme\rc\transparent.png' does not exist.

**Comment by dpizetta** [comment]
Hi @sabrabano0, are you downloading the repo? 

Because those files are there for both themes: 
https://github.com/ColinDuquesnoy/QDarkStyleSheet/blob/master/qdarkstyle/light/rc/transparent.png
https://github.com/ColinDuquesnoy/QDarkStyleSheet/blob/master/qdarkstyle/dark/rc/transparent.png

Could you please check again? Tks

**Comment by dpizetta** [comment]
Closing by lack of response and it seems to be solved as the file is there.
