### ISSUE TITLE
Incoherent focus colors

### ISSUE THREAD

**Issue by PlasmaMichael** [ColinDuquesnoy/QDarkStyleSheet#31]
Focus png of radio and checkbox are too bright than the color used in the stylesheet for QWidget which is #78879b.

**Comment by ColinDuquesnoy** [comment]
The focus color of the png is not too bright, this was my intention to use that color for every widget but I guess I missed some. So when I am going to fix this issue, I'll use the same color as the png instead of #78879b. 

Again, this color has been chosen based on the new kde breeze theme which I like very much and don't plan to change.

**Comment by DreamMichael** [comment]
I tried to change using the actual focus color and it's very dark, the bright color looks better.

**Comment by ColinDuquesnoy** [comment]
Fixed. The whole color scheme got an update and every widget should now use the bright focus color.
