### ISSUE TITLE
Status bar widgets have an outline

### ISSUE THREAD

**Issue by goanpeca** [ColinDuquesnoy/QDarkStyleSheet#36]
Hey @ColinDuquesnoy awesome work :-)

Using it in Spyder, and noticed that the status bar widgets have an outline. I dont think this is intended right?

![image](https://cloud.githubusercontent.com/assets/3627835/16793169/6d99d0e0-4894-11e6-9750-e8fc0bddf16d.png)

**Comment by ColinDuquesnoy** [comment]
Hi  @goanpeca 

Yes this is not intended. I've tried your feature/qdarkstyle branch on my dev system (KDE Plasma 5.7.0/Qt 5.7.0/PyQt 5.6 dev snapshot) and I can reproduce the problem. I don't understand what's happening because I have no issue in OpenCobolIDE.

![screenshot_20160713_204852](https://cloud.githubusercontent.com/assets/1681217/16815723/3deb20ea-493b-11e6-9aad-7ba74fcb360c.png)

What is the type of your status bar widgets? QLabels? 
Can you point me to where you add those widgets and where you setup the stylesheet?

FYI, here is where I setup the stylesheet in OCIDE: https://github.com/OpenCobolIDE/OpenCobolIDE/blob/master/open_cobol_ide/app.py#L131. 
And here is where I setup the status bar widgets: https://github.com/OpenCobolIDE/OpenCobolIDE/blob/master/open_cobol_ide/controllers/edit.py#L104

**Comment by goanpeca** [comment]
They are more complex widgets based on QWidget.

https://github.com/spyder-ide/spyder/blob/master/spyderlib/widgets/status.py

**Comment by ColinDuquesnoy** [comment]
Thanks, I'll have a look ASAP.

**Comment by ColinDuquesnoy** [comment]
Should be fixed in master branch.

![screenshot_20160717_153141](https://cloud.githubusercontent.com/assets/1681217/16900925/1177a7bc-4c34-11e6-9f07-398e6e847720.png)


But I have an issue with pyside. The linux distribution I am using has removed pyside (and pyqt4) because Qt4 is not supported anymore. As such I cannot recompile the stylsheet's resource file for pyside... May I ask you to recompile it for pyside (you just need to run [compile_qrc.py](https://github.com/ColinDuquesnoy/QDarkStyleSheet/blob/master/qdarkstyle/compile_qrc.py) with the pyside tools installed on your system).

**Comment by ColinDuquesnoy** [comment]
@goanpeca I managed to install pyqide from pypi so no need for a PR for the pyside qrc file. I'll release a new version on pypi soon.

**Comment by goanpeca** [comment]
Ok @colinduquesnoy. thabks a lot :)
