### ISSUE TITLE
ImportError: No module named setuptools

### ISSUE THREAD

**Issue by libBletchley** [ColinDuquesnoy/QDarkStyleSheet#50]
There is no debian package for _QDarkStyleSheet_ so I did a `git clone`.  Then ran: $ `python setup.py install`.

Output is:

`
Traceback (most recent call last):
  File "setup.py", line 29, in <module>
    from setuptools import setup, find_packages
ImportError: No module named setuptools
`

**Comment by ColinDuquesnoy** [comment]
You miss the [python-setuptools](https://packages.debian.org/fr/sid/python-setuptools) package. Nowadays, this package is the default python packaging tool. You'll need it to install almost every python package, that's why it is not listed in the package dependencies. I am surprised it is not part of the default python install.
