### ISSUE TITLE
[Linux] FileDialog Icons are miniature (look like dots)

### ISSUE THREAD

**Issue by Bururik** [ColinDuquesnoy/QDarkStyleSheet#85]
When using QFileDialog in either Ubuntu 16.04 (unity) or CentOS7 (gnome) the dialog's icons look like dots. This appears to be similar to issue #51, although I'm not having much luck with the "fix" provided, and the dialog's icons in Windows 10 appear to be fine.

![screenshot from 2018-03-06 12-37-40](https://user-images.githubusercontent.com/22623136/37051479-29b89730-213c-11e8-970c-a0b8a68e281e.png)

**Comment by dpizetta** [comment]
I will take a look, tks. Can you send us a piece of code where it occurs that I can use to test here (just a dialog)? I have Ubuntu 16.04, but with both Gnome and Unity. Tks

**Comment by Bururik** [comment]
wow, hang on....I think I may have just found my own fix, it looks as though I had a problem with inheritance of QTableWidget and QMainWindow (I've been spending days on this problem).

for the code that breaks it (darkstyleBreak.py):
https://gist.github.com/Bururik/f2d79b9e8c8860bf0040878f94c358ee#file-darkstylebreak-py

for the code that "fixes" it (darkstyleFix.py)
https://gist.github.com/Bururik/f2d79b9e8c8860bf0040878f94c358ee#file-darkstylefix-py

although IDK if its a real fix since qdarkstyle with the --no_dark  tag (the default style) shows up regularly with the "[darkstyleBreak.py](https://gist.github.com/Bururik/f2d79b9e8c8860bf0040878f94c358ee#file-darkstylebreak-py)" file as seen here:

![screenshot from 2018-03-06 14-45-03](https://user-images.githubusercontent.com/22623136/37058443-2557cc42-2150-11e8-95f6-d3a348690eca.png)

**Comment by dpizetta** [comment]
Hi, both codes work here in Ubuntu 16.04 Gnome, I've just commented line 56 `self.setItem(row, column, item)`, because shows an error that 'self' does not have this method. Btw, Both worked. 

For me, the second code (your fix) seems to be more logical with the open dialog in the main window. 

In the past, I have some problems with dialogs, try to use this option [QFileDialog::DontUseNativeDialog](http://doc.qt.io/qt-5/qfiledialog.html#Option-enum). 

I will try more tests here including over Unity distro.

**Comment by dpizetta** [comment]
Closing for now, if necessary, reopen.
